### PR TITLE
Prepare the release of version 1.4.0

### LINKED ISSUE #70: Test with WP 5.6
WordPress 5.6 will be here soon. Time for us to check, if our plugins are compatible 🥳

- [x] test with the current WP 5.6 RC
- [x] add `Tested up to: 5.6` to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

### PR DESCRIPTION
**Pull request by patrickrobrecht**
- Prepare the release of version 1.4.0 (update stable tag and changelog README.md)
- Declare WP 5.6 compatibility (Fixes #70)
- Update links to link pluginkollektiv.org and antivirus.pluginkollektiv.org respectively

### CODE REVIEW

**Comment by stklcode** [comment]
Target branch `develop` intentionally set, i.e. postpone stable merge?

**Comment by stklcode** [comment]
Tested on latest WP 5.6 / PHP 8.0 :heavy_check_mark: 

* installs without problems
* checks work as expected
* custom SafeBrowsing key is used
* error messages (wrong key, violated key restriction, ...) are displayed correctly in the error mail

**Comment by patrickrobrecht** [comment]
> Target branch `develop` intentionally set, i.e. postpone stable merge?

Yes, I intended to merge this PR into `develop` with "Squash and merge" as done for the features as well and merge `develop` into `stable` with "Create and merge" directly after that. In my opinion this leads to a clean commit history as `stable` is `develop` + merge commit for every release (or hotfix/readme update) then.

**Review by stklcode — APPROVED** [review]

**Comment by stklcode** [comment]
Just made some last-minutes changes to the deployment configuration to not deploy any test stuff.

Simulated deployment (more or less what the GH actions do):
```
$ git clone https://github.com/pluginkollektiv/antivirus.git .
$ composer install
$ rsync -rc --exclude-from=".distignore" "./" "/tmp/antivirus-target" --delete --delete-excluded
$ tree -a /tmp/antivirus-target
/tmp/antivirus-target
├── antivirus.php
├── CHANGELOG.md
├── css
│   ├── style.css
│   └── style.min.css
├── inc
│   ├── class-antivirus-checkinternals.php
│   ├── class-antivirus-checksumverifier.php
│   ├── class-antivirus.php
│   └── class-antivirus-safebrowsing.php
├── js
│   ├── script.js
│   └── script.min.js
├── LICENSE.txt
└── README.md

3 directories, 12 files
```

**Pull request merged**
