### PR TITLE
Update code style checks, tests, build and deployment

### LINKED ISSUE #18: Add unit tests for most of the existing functionality
This means a lot of refactoring due to how the plugin is set up currently, but it's very important to guarantee functionality and enable enhancements in the future.

### PR DESCRIPTION
**Pull request by patrickrobrecht**
- Add code style check for CSS
- Update code style checks for JS and PHP
- Generate minified files in build step and remove them from the repository
- Update PHP versions in Travis build
- Update GitHub Actions to the new branch structure

### CODE REVIEW

**Review by stklcode — COMMENTED** [review]
Changes seem reasonable to me.

But is there any reason to keep this block in _.travis.yml_ (except the `composer install ...` of course)?
```yaml
before_script:
  # Setup Coveralls
  - phpenv local 5.5
  - composer install --no-interaction
  - phpenv local --unset
```

The comment is bogus, as we don't setup Coveralls here, but I don't see any arguments for the PHP 5.5 switch in current setup. Installs fine with 5.6 through 7.4

**Comment by patrickrobrecht** [comment]
> The comment is bogus, as we don't setup Coveralls here, but I don't see any arguments for the PHP 5.5 switch in current setup. Installs fine with 5.6 through 7.4

<del>To be honest, I haven't checked this as the tests aren't executed anyway because the Travis build isn't triggered (see discussion on Slack).</del>

The Travis build is running now, but the build fails:

- The PHP dependencies can only be fulfilled on PHP 7.2+, that's why the build fails for PHP 5.6 - 7.1
- The installed WordPress cannot connect to the database, that's why the test step fails.

**Comment by stklcode** [comment]
> The PHP dependencies can only be fulfilled on PHP 7.2+, that's why the build fails for PHP 5.6 - 7.1

We have to downgrade to PHPUnit 5. I've rebuilt the composer lockfile for compatibility, but we might discuss if we _really_ need to run 14 tests. We yet trust the static compatibility analysis for 5.2-5.5...

> The installed WordPress cannot connect to the database, that's why the test step fails.

The easy part, missing _MySQL_ service.

**Comment by stklcode** [comment]
I've reworked the unit tests. We now mock the entire WP environment and run separate tests on the plugin itself and the test modules (only Safe Browsing so far, I just migrated existing test cases)

The tests still fail because of real issues (see #69), so I's assume they're doing their job.

**Pull request merged**
