### PR TITLE
Issue 10 - add space to 'file'-regex-part to reduce false positives

### PR DESCRIPTION
**Pull request by websupporter**
Would solve https://github.com/pluginkollektiv/antivirus/issues/10

It's just a suggestion. This change would still catch the usage of `file()`, but maybe there was more thought involved than just prohibit this function to use.

### CODE REVIEW

**Comment by Zodiac1978** [comment]
@websupporter This wouldn't find any usages of `file` on the beginning of a line or with tabs, or not?

Would it be more helpful to use something like this?
`file(.*)\(`

**Comment by websupporter** [comment]
@Zodiac1978 sounds reasonable.

**Comment by 2ndkauboy** [comment]
I think `\bfile\b` should do the trick: https://regex101.com/r/q4mTNX/1

**Comment by 2ndkauboy** [comment]
I wonder if we shouldn't "work-match" all functions names: https://regex101.com/r/q4mTNX/2

**Comment by Zodiac1978** [comment]
Yes `\b` does the trick. But just for my knowledge gain: Why do we need the second `\b`? Wouldn't the first one suffice here?

**Comment by 2ndkauboy** [comment]
See: https://www.regular-expressions.info/wordboundaries.html

**Comment by 2ndkauboy** [comment]
Closes #10.

**Pull request merged**
