### PR TITLE
Update links from Google+ to GitHub wiki

### PR DESCRIPTION
**Pull request by 2ndkauboy**
I've created a `news` branch in the wiki with the archived Google+ pages. When the wiki branch is merged, this PR would link to the new news pages.

### CODE REVIEW

**Review by bueltge — APPROVED** [review]

**Comment by bueltge** [comment]
We should release them because G+ is dead and the links to GitHub are much more helpful.

**Comment by krafit** [comment]
I'll migrate these to our dedicated antivirus Website

**Review by patrickrobrecht — CHANGES_REQUESTED** [review]
The new links point to not existing pages in the Antispam Bee (sic!) Wiki. 

@krafit https://antivirus.pluginkollektiv.org/ does not show the documentation either.

**Comment by stklcode** [comment]
If the documentation location changes we should not forget to update the link on the settings page and the _README.md_

https://github.com/pluginkollektiv/antivirus/blob/8b3e1045c48ac4cd2c088003b1d3e61f041940bb/inc/class-antivirus.php#L791-L795

**Comment by patrickrobrecht** [comment]
Closed in favor of #78. Wiki pages are replaced with a link to the documentation on the website.

**Pull request closed without merging**
